### PR TITLE
Update the LICENSE to use one MIT at the top

### PR DESCRIPTION
**Pull request by certik**

### CODE REVIEW

**Comment by certik** [comment]
The original file was using Windows (?) encoding, thus the larger diff.

**Review by awvwgk — APPROVED** [review]

**Comment by awvwgk** [comment]
Maybe we should also try to resolve #9 while we are on it already.

**Comment by certik** [comment]
> Maybe we should also try to resolve #9 while we are on it already.

Sure: #25.

**Review by milancurcic — APPROVED** [review]

**Comment by certik** [comment]
@jacobwilliams can you please approve it (or not), so that we can merge this?

**Review by jacobwilliams — APPROVED** [review]
Yep, agree to change license to plain MIT.

**Pull request merged**
